---
abstract: 'PostgreSQL runner for tests'
author:
  - 'Toby Corkindale'
build_requires:
  DBD::Pg: 0
  DBI: 0
  ExtUtils::MakeMaker: 6.59
  Test::SharedFork: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-PostgreSQL
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Lite: 0
  Time::HiRes: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
